services:
  nest-api:
    build:
      context: .
      dockerfile: docker/nest-api/Dockerfile
    container_name: nest-api
    volumes:
      - ./src/nest-api:/usr/src/nest-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
